http:
  middlewares:
    SslHeader:
      headers:
        FrameDeny: true
        AccessControlAllowMethods: 'GET,OPTIONS,PUT'
        AccessControlAllowOriginList:
          - origin-list-or-null
        AccessControlMaxAge: 100
        AddVaryHeader: true
        BrowserXssFilter: true
        ContentTypeNosniff: true
        ForceSTSHeader: true
        STSIncludeSubdomains: true
        STSPreload: true
        #ContentSecurityPolicy: default-src *; img-src *
        ContentSecurityPolicy: default-src 'self' 'unsafe-inline' *.{{env "DOMAINNAME"}}; script-src 'self' 'unsafe-inline' 'unsafe-eval' grafana.{{env "DOMAINNAME"}}
        CustomFrameOptionsValue: SAMEORIGIN
        ReferrerPolicy: same-origin
        PermissionsPolicy: vibrate 'self'
        STSSeconds: 315360000
